name: bybit_clone
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  http: ^1.0.0
  injectable: ^2.1.2
  equatable: ^2.0.5
  flutter_svg: ^2.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.4.4
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - asset/fonts/
    - asset/icons/
    - asset/images/

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: asset/fonts/IBMPlexSans-Thin.ttf
          weight: 100
        - asset: asset/fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: asset/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: asset/fonts/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: asset/fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: asset/fonts/IBMPlexSans-Bold.ttf
          weight: 700